# Jekyll Configuration
title: "🌱 Urban Garden Pro"
description: "Transform your apartment into an urban garden paradise. Expert tips, product reviews, and affiliate recommendations."
baseurl: "/my-ai-blog"
url: "https://kokman078.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  posts:
    output: true

# Show future posts (important for scheduled content)
future: true

# Monetization
monetization:
  google_adsense:
    enabled: true
    publisher_id: "ca-pub-7298798192334573"
  google_analytics: "G-WQ33YZNRCQ"
amazon_associate_tag: kokman-20

# Email Marketing (set your real Mailchimp form action URL here)
mailchimp:
  form_url: "https://urbangardenpro.us1.list-manage.com/subscribe/post?u=abc123&id=def456"

# SEO
author: Urban Garden Pro
twitter:
  username: urbangardenpro
  card: summary_large_image

# Social Links  
social:
  name: Urban Garden Pro
  links:
    - https://urbangardenpro.com

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
